namespace :message_template do
  desc "TODO"
  task create: :environment do
    NotificationMessageTemplate.where(code: "template1").first_or_create(title: 'User Registers', path:"user_message/verify_code", body: "Please enter the following verification code to activate your account at www.AuctionMyDeal.com.  Verification Code: {user_verification_code} ")

    NotificationMessageTemplate.where(code: "template2").first_or_create(title: 'Welcome Email for Verified account', path:"user_message/welcome", body: "Thank you for registering as a free member at www.AuctionMyDeal.com!  Your account has been verified and we look forward to helping you grow your real estate investment business in 2020 and beyond.")

    NotificationMessageTemplate.where(code: "template3").first_or_create(title: 'Forget Password', path:"user_message/forget_password", body: "We heard you need a password reset. Click the link below and you'll be redirected to a secure site from which you can set a new password. \n {password_reset_path} \n If you didn't try to reset your password then ignore this email. \n Best Regards, \n Your Support Team @ \n AuctionMyDeal.com")

    NotificationMessageTemplate.where(code: "template4").first_or_create(title: 'Seller has submitted a property', path:"property_message/under_review", body: "Thank you for submitting your property at {property_address}!  You will get an email and a message in your user dashboard that will advise you when your property is approved or if we have any questions. To Your Success, \n Your Support Team @ \n AuctionMyDeal.com ")

    # NotificationMessageTemplate.where(code: "template5").first_or_create(title: 'Seller’s property has been approved by admin', path:"property_mailer/approved", body: 'The property you submitted at {property_address} has been approved! Check your email we just sent you that gives you')

    NotificationMessageTemplate.where(code: "template6").first_or_create(title: 'Seller’s property has been approved by admin and is now active under Best Offer System', path:"property_message/best_offer", body: "The property you submitted at {property_address} has been approved! Check your email we just sent you that gives you")

    NotificationMessageTemplate.where(code: "template7").first_or_create(title: 'Seller’s property is on "Live Online Auction" status', path:"property_message/live_bidding", body: "The property you submitted at {property_address} is now active for Live Online Bidding status.")

    NotificationMessageTemplate.where(code: "template8").first_or_create(title: 'Seller\'s property is in "Post Auction" status', path:"property_message/post_auction", body: "The property you submitted at {property_address} is now in post auction status so go to your user panel at AuctionMyDeal.com to accept, counter or relist your property under Best Offer or Live Online Auction?")

    NotificationMessageTemplate.where(code: "template9").first_or_create(title: 'Buy Now Email Template: ', path:"property_message/buy_now_notification", body: "Congratulations!!! You just got a buyer willing to pay your “Buy Now” price for your property at {property_address}.  Your property is now in pending auction status until you go to your user panel at AuctionMyDeal.com to accept your “Buy Now” offer!  Your Support Team @ AuctionMyDeal.com")

    NotificationMessageTemplate.where(code: "template10").first_or_create(title: 'Seller’s property is in “Sold” status', path:"property_message/sold_notification", body: "Congratulations on selling your property at {property_address}!!!  Our goal is to go the extra yard for our members and we would like to learn from every property that’s posted on our site so that we can learn from our successes and failures.  It would mean a lot if you would take just a minute or 2 to give us your honest feedback? \n Your Support Team @ \n AuctionMyDeal.com")


    # NotificationMessageTemplate.where(code: "template11").first_or_create(title: 'Seller’s property has Hold by admin',subject: 'AuctionMyDeal.com needs Your Help',partial: false, format: "html", locale: "en", handler: "erb", path:"property_mailer/hold_notification", body: '<b>Hello <%= @user.first_name %>,</b><p style="font-size: 13px;">Your property at <%= @property.address %> has temporarily been put on hold until you correct the following:</p><p style="font-size: 13px;">Once you correct the following then let us know what we can do to help you get it activated as soon as possible.</p><p style="font-size: 13px;">We look forward to getting you back on track soon!...:)</p><p style="font-size: 13px; margin: 0px;">Your Support Team @</p><p style="font-size: 13px; margin: 0px;">AuctionMyDeal.com</p>')


    NotificationMessageTemplate.where(code: "template12").first_or_create(title: 'Seller’s property has Terminated', path:"property_message/termination_notification", body: "We noticed that your terminated your property at {property_address} so let us know if there’s anything we can do to help you? Your Support Team @ AuctionMyDeal.com…:)")


    NotificationMessageTemplate.where(code: "template13").first_or_create(title: 'Buyer has submitted an offer on the site under Best Offer', path:"property_message/buyer_best_offer_notification", body: "Thank you for your Best Offer on {property_address} at AuctionMyDeal.com.  The seller is considering your offer and will be letting you know if your offer is acceptable or not.  They have the option to accept, reject or counter your offer, so look for a message from them in your messages under your profile?")



    # NotificationMessageTemplate.where(code: "template14").first_or_create(title: 'Buyers offer didn\'t get accepted and property is now in Live Online Auction',subject: 'Are you still interested in buying property_address???.',partial: false, format: "html", locale: "en", handler: "erb", path:"best_offer_mailer/not_accepted", body: '<b>Hello <%= @buyer.first_name %>,</b><p style="font-size: 13px;">Thanks again for making your “Best Offer” for <%= @property.address %>, but unfortunately the seller didn’t accept your offer during the “Best Offer” time frame.</p><p style="font-size: 13px;">If you’re still interested in this property then we highly suggest that you make an offer during the Live Online Auction so that you still have a chance to buy this property?</p><p style="font-size: 13px;">You can view the property and make your bid at <%= link_to "#{@property.address}", "#{APP_CONFIG["site_url"]}/property/#{@property.unique_address}", style: "color: #28608f;" %>.</p><p style="font-size: 13px;">You should at least offer your the same price you did during the Best Offer timer if you’re interested in buying this property and hopefully You will be the WINNING Bidder this time.</p><p style="font-size: 13px; margin: 0px;">To Your Success!</p><p style="font-size: 13px; margin: 0px;">Your Support Team @</p><p style="font-size: 13px; margin: 0px;">AuctionMyDeal.com</p><p style="font-size: 13px;">P.S.: Please let us know if you have any questions, suggestions or feedback on how we can make this site better serve you? <%= link_to "Click HERE", "#{APP_CONFIG["site_url"]}/help-and-faq", style: "color: #28608f;" %></p>')


    # NotificationMessageTemplate.where(code: "template15").first_or_create(title: 'Bidder was out bid at the end of the Best Offer timer',subject: 'property_address is now Pending.',partial: false, format: "html", locale: "en", handler: "erb", path:"best_offer_mailer/out_bidded", body: '<b>Hello <%= @buyer.first_name %>,</b><p style="font-size: 13px;">We are sorry to inform you that you were not the “Best Offer” for the property at <%= @property.address %>.</p><p style="font-size: 13px;">There’s always a chance that it might come on the market and we will let you know if it does, but at this current time the seller is verifying the buyers ability to close and then will finalize all paperwork and get property into the title company.</p><p style="font-size: 13px;">There will be many more properties that we hope you are able to buy on this site so make sure you sign up for our automatic updates so you get priority access to the Best Deals! To sign up for this list click VIP Buyers List!</p><p style="font-size: 13px;">To Your Success!</p><p style="font-size: 13px; margin: 0px;">Your Support Team @</p><p style="font-size: 13px; margin: 0px;">AuctionMyDeal.com</p><p style="font-size: 13px;">P.S.: We would appreciate your feedback on your experience using this site so that we can make it better. Please <%= link_to "Click HERE", "#{APP_CONFIG["site_url"]}/help-and-faq", style: "color: #28608f;", style: "color: #28608f;" %> if you’re willing to provide us feedback?</p>')


    # NotificationMessageTemplate.where(code: "template16").first_or_create(title: 'Bidder was out bid at the end of the Live Auction',subject: 'property_address is now Pending.',partial: false, format: "html", locale: "en", handler: "erb", path:"bid_mailer/out_bidded", body: '<b>Hello <%= @buyer.first_name %>,</b><p style="font-size: 13px;">We are sorry to inform you that you were not the “Best Offer” for the property at <%= @property.address %>.</p><p style="font-size: 13px;">There’s always a chance that it might come on the market and we will let you know if it does, but at this current time the seller is verifying the buyers ability to close and then will finalize all paperwork and get property into the title company.</p><p style="font-size: 13px;">There will be many more properties that we hope you are able to buy on this site so make sure you sign up for our automatic updates so you get priority access to the Best Deals! To sign up for this list click VIP Buyers List!</p><p style="font-size: 13px;">To Your Success!</p><p style="font-size: 13px; margin: 0px;">Your Support Team @</p><p style="font-size: 13px; margin: 0px;">AuctionMyDeal.com</p><p style="font-size: 13px;">P.S.: We would appreciate your feedback on your experience using this site so that we can make it better. Please <%= link_to "Click HERE", "#{APP_CONFIG["site_url"]}/help-and-faq", style: "color: #28608f;" , style: "color: #28608f;" %> if you’re willing to provide us feedback?</p>')


    # NotificationMessageTemplate.where(code: "template17").first_or_create(title: 'Buyer has submitted a bid under Live Online Auction',subject: 'Thank you for Your Offer on property_address!',partial: false, format: "html", locale: "en", handler: "erb", path:"bid_mailer/submitted", body: '<b>Hello <%= @buyer.first_name %>,</b><p style="font-size: 13px;">Thank you for submitting a bid on <%= @property.address %> at AuctionMyDeal.com!</p><p style="font-size: 13px;">You are currently the Highest Bidder so watch the timer to make sure you don’t get outbid.</p><p style="font-size: 13px;">The seller will be contacting the Winning Bidder at the end of the auction to finalize the paperwork.</p><p style="font-size: 13px;">Best Wishes in Winning this Property!!!</p><p style="font-size: 13px; margin: 0px;">Your Support Team @</p><p style="font-size: 13px; margin: 0px;">AuctionMyDeal.com</p><p style="font-size: 13px;">P.S.: The Seller has the right to choose any offer whether the offer is the Highest Price or offers the best terms. Sellers may consider cash offers stronger than financing so please make sure you provide proof of funds and/or pre-approval status to make sure your offer is as strong as possible.</p><p style="font-size: 13px;">P.S.: Please let us know if you have any questions or suggestions? <%= link_to "Click HERE", "#{APP_CONFIG["site_url"]}/help-and-faq", style: "color: #28608f;" %></p>')



    # NotificationMessageTemplate.where(code: "template18").first_or_create(title: 'Buyer chooses the “Buy Now” option',subject: 'Congrats for choosing to “BUY NOW” @ AuctionMyDeal.com', partial: false, format: "html", locale: "en", handler: "erb", path:"buy_now_mailer/submitted", body: '<b>Hello <%= @buyer.first_name %>,</b><p style="font-size: 13px;">Thank you for choosing the “Buy Now” option for the property at <%= @property.address %> at AuctionMyDeal.com!</p><p style="font-size: 13px;">The property is now pending and taken off the market for You until the seller verifies your proof of funds and/or pre-approval. Once they verify this information they will get back in touch with you to execute your contract or to verify more information from you.</p><p style="font-size: 13px;">Please let us know if you have any questions or there’s anything we can do to help you get this property closed? <%= link_to "Click HERE", "#{APP_CONFIG["site_url"]}/help-and-faq", style: "color: #28608f;" %> for Help</p><p style="font-size: 13px; margin: 0px;">Your Support Team @</p><p style="font-size: 13px; margin: 0px;">AuctionMyDeal.com</p><p style="font-size: 13px;">P.S.: The Seller has the right to accept or reject any offer based upon not only price but also terms and proving the buyers ability to buy. Sellers may consider cash offers stronger than financing so please make sure you provide proof of funds and/or pre-approval status to make sure your offer is as strong as possible. Nothing is final until seller and buyer executed a sales contract and a deposit is given to seller or delivered to the title company.</p>')


    NotificationMessageTemplate.where(code: "template19").first_or_create(title: ' Highest Bidder to a property which the live online bidding has already ended.',path:"bid_message/highest_bidder_notification", body: "Congratulations for being the Highest Bidder for {property_address}!!!  You should be getting a message from the seller in regards to finalizing a contract or providing more information to them.  Check your messages in your profile and if you don’t hear from the seller within 24 hours please let us know? To Your Success, \n Your Support Team @ \n AuctionMyDeal.com")



    NotificationMessageTemplate.where(code: "template20").first_or_create(title: '(buyer) who save/favorite the property which the live online bidding has already ended', path:"property_message/watchers_post_notification", body: "The property at {property_address} is now pending or off the market, but we will let you know if it comes back on the market.  Your Support Team @ AuctionMyDeal.com")



    # NotificationMessageTemplate.where(code: "template21").first_or_create(title: 'Users who bid to a property that the property has been Buy Now by the other buyer in the site.',subject: 'You’ve been Outbid for property_address',partial: false, format: "html", locale: "en", handler: "erb", path:"buy_now_mailer/out_bidded_notification", body: '<b>Hello <%= @buyer.first_name %>,</b><p style="font-size: 13px;">Thank you for making your “Best Offer” or Bid on <%= @property.address %> at AuctionMyDeal.com!</p></p><p style="font-size: 13px;">Unfortunately, there’s a buyer who has chosen to buy the property for the “Buy Now” price.</p><p style="font-size: 13px;">The seller is verifying all of this buyers information, but if this property comes back on the market you will be one of the first to know about it.</p><p style="font-size: 13px;">Please answer the following information by Clicking Here?</p><p style="font-size: 13px;">If this property comes back on the market to you want to be considered a back up contract?</p><p style="font-size: 13px;">If this deal falls apart and the seller didn’t repost this property for Live Online Bidding what’s your highest price you would be willing to pay for this property if you didn’t have to compete with other buyers?</p><p style="font-size: 13px;">When is the soonest that you can close on this property?</p><p style="font-size: 13px;">Will you be paying cash, line of credit, Hard Money or other type of financing? Please explain?</p><p style="font-size: 13px;">To Your Success!</p><p style="font-size: 13px; margin: 0px;">Your Support Team @</p><p style="font-size: 13px; margin: 0px;">AuctionMyDeal.com</p>')


    # NotificationMessageTemplate.where(code: "template22").first_or_create(title: 'Users who bid to a property that the property has been terminated by the seller.',subject: 'property_address is no longer on the Market',partial: false, format: "html", locale: "en", handler: "erb", path:"bid_mailer/termination_notification", body: '<b style="font-size: 13px;">Hello <%= @buyer.first_name %></b><p style="font-size: 13px;">The property you bid on at <%= @property.address %> has been terminated from the market, but we will let you know if it comes back on.</p><p style="font-size: 13px;"> The seller has decided that it’s not in their best interest to sell this property at this current time.</p><p style="font-size: 13px;">Please let us know you have any questions about this property or if there’s anything else we can do to help you? <%= link_to "Click HERE", "#{APP_CONFIG["site_url"]}/help-and-faq", style: "color: #28608f;" %> for Support!</p><p style="font-size: 13px;">To Your Success!</p><p style="font-size: 13px; margin: 0px;">Your Support Team @</p><p style="font-size: 13px; margin: 0px;">AuctionMyDeal.com</p>')


    # NotificationMessageTemplate.where(code: "template23").first_or_create(title: 'Users who bid to a property that the property has been withdrawn by the seller',subject: 'property_address is no longer on the Market', partial: false, format: "html", locale: "en", handler: "erb", path:"bid_mailer/withdraw_notification", body: '<b style="font-size: 13px;">Hello <%= @buyer.first_name %></b><p style="font-size: 13px;">The property you bid on at <%= @property.address %> has been withdrawn from the market, but we will let you know if it comes back on.</p><p style="font-size: 13px;">Please let us know you have any questions about this property or if there’s anything else we can do to help you? <%= link_to "Click HERE", "#{APP_CONFIG["site_url"]}/help-and-faq", style: "color: #28608f;" %> for Support!</p><p style="font-size: 13px;">To Your Success!</p><p style="font-size: 13px; margin: 0px;">Your Support Team @</p><p style="font-size: 13px; margin: 0px;">AuctionMyDeal.com</p>')


    NotificationMessageTemplate.where(code: "template24").first_or_create(title: 'Seller has received a message on the site', path:"property_message/chat_notification", body: "You have received a message at AuctionMyDeal.com.")

    NotificationMessageTemplate.where(code: "template25").first_or_create(title: 'Urgent  message ', path:"property_message/urgent_chat_notification", body: "You have an unread Urgent message(s) for {property_address} in Auctionmydeal.com site.")

    # NotificationMessageTemplate.where(code: "template25").first_or_create(title: '(buyer) who save/favorite the property which the live online bidding has already ended', path:"property_message/watchers_post_notification", body: 'The property at {property_address} is now pending or off the market, but we will let you know if it comes back on the market.  Your Support Team @ AuctionMyDeal.com')

  end
end
