development:
  stripe_secret_key: 'sk_test_GVSXPLylTfKFdNWGsIkROaRA00KJZI8h3k'
  stripe_publishable_key: 'pk_test_4sZnz5s0YULtXM1QlM7PNMKB00I1O8AU0m'

production:
  stripe_secret_key: 'production s_key'
  stripe_publishable_key: 'production p_key'
