development:
  stripe_secret_key: 'sk_test_OPlgFcR75jwHK9C7LJEPinfM00a2WZQpX1'
  stripe_publishable_key: 'pk_test_x1v7Sm8JVBUJnaIj2odZlfSR00JehxacaE'

production:
  stripe_secret_key: 'sk_test_GVSXPLylTfKFdNWGsIkROaRA00KJZI8h3k'
  stripe_publishable_key: 'pk_test_4sZnz5s0YULtXM1QlM7PNMKB00I1O8AU0m'
